pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('netflix-clone-app') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('netflix-clone-app') {
                    sh 'npm run build'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}
