pipeline {
    agent any

    environment {
    SCANNER_HOME = tool 'SonarScanner'
    NODEJS_HOME = tool 'NodeJS18'
    PATH = "${NODEJS_HOME}/bin:${env.PATH}"
}

    stages {

        stage('Install Dependencies') {
            steps {
                dir('netflix-clone-app') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('netflix-clone-app') {
                    sh 'npm run build'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('netflix-clone-app') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.projectKey=Netflix-Clone \
                        -Dsonar.projectName="Netflix Clone" \
                        -Dsonar.sources=src
                        """
                    }
                }
            }
        }

        stage('OWASP Dependency Check') {
            steps {
                dir('netflix-clone-app') {
                    dependencyCheck(
                        odcInstallation: 'OWASP',
                        additionalArguments: '--scan .'
                    )
                }
            }
        }

        stage('Publish OWASP Report') {
            steps {
                dependencyCheckPublisher(
                    pattern: '**/dependency-check-report.xml'
                )
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed. Check console output.'
        }
    }
}
